/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ry_dialry_demo01_ndk_NDKActivity */

#ifndef _Included_cn_ry_dialry_demo01_ndk_NDKActivity
#define _Included_cn_ry_dialry_demo01_ndk_NDKActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_ry_dialry_demo01_ndk_NDKActivity
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_ry_dialry_demo01_ndk_NDKActivity_getStringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
