/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_loovee_common_jni_ConstantJNI */

#ifndef _Included_com_loovee_common_jni_ConstantJNI
#define _Included_com_loovee_common_jni_ConstantJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_loovee_common_jni_ConstantJNI
 * Method:    getEncryptKeyFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loovee_common_jni_ConstantJNI_getEncryptKeyFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
